-- 1. Add designation column to employees table
ALTER TABLE public.employees 
ADD COLUMN IF NOT EXISTS designation text DEFAULT 'Employee';

-- 2. Create the leave_requests table
CREATE TABLE IF NOT EXISTS public.leave_requests (
    id bigint generated by default as identity primary key,
    employee_id bigint references public.employees(employee_id) on delete cascade,
    company_id bigint references public.companys(id) on delete cascade,
    start_date date not null,
    end_date date not null,
    reason text,
    status text default 'Pending', -- Can be 'Pending', 'Approved', 'Rejected'
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Note: Enable Row Level Security (RLS) if you are using it in your Supabase project.
-- ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;
