-- 1. Add daily_rate and role to employees table
ALTER TABLE public.employees 
ADD COLUMN IF NOT EXISTS daily_rate numeric DEFAULT 1000.00;

ALTER TABLE public.employees
ADD COLUMN IF NOT EXISTS role text DEFAULT 'Employee';

-- 2. Create the offices table
CREATE TABLE IF NOT EXISTS public.offices (
    id bigint generated by default as identity primary key,
    company_id bigint references public.companys(id) on delete cascade,
    office_name text not null,
    latitude double precision not null,
    longitude double precision not null,
    radius integer not null default 100,
    timezone text default 'UTC',
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. Create the verification_events table
CREATE TABLE IF NOT EXISTS public.verification_events (
    id bigint generated by default as identity primary key,
    employee_id bigint references public.employees(employee_id) on delete cascade,
    step_name text not null,
    pass_fail boolean not null,
    score double precision,
    failure_reason text,
    device_id text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. Create the attendance_overrides table (HR Review Queue)
CREATE TABLE IF NOT EXISTS public.attendance_overrides (
    id bigint generated by default as identity primary key,
    employee_id bigint references public.employees(employee_id) on delete cascade,
    company_id bigint references public.companys(id) on delete cascade,
    failed_event_id bigint references public.verification_events(id),
    status text default 'Pending', -- 'Pending', 'Approved', 'Rejected', 'Recheck'
    hr_notes text,
    reviewer_id bigint, -- company_id or hr_employee_id
    created_at timestamp with time zone default timezone('utc'::text, now()),
    resolved_at timestamp with time zone
);

-- 5. Create the audit_logs table for Hardening
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint generated by default as identity primary key,
    action_type text not null, -- e.g., 'override_attendance', 'update_settings', 'login'
    user_id bigint, -- Can be company_id or employee_id depending on context
    user_role text, -- 'company', 'admin', 'hr', 'employee'
    details jsonb, -- Additional metadata like before/after state
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Note: If your Supabase project enables RLS by default, you MUST run these to allow the API to access the tables:
ALTER TABLE public.audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.offices DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.verification_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_overrides DISABLE ROW LEVEL SECURITY;

-- Alternatively, if you want to keep RLS enabled, run these permissive policies:
-- CREATE POLICY "Allow all operations" ON public.offices FOR ALL USING (true) WITH CHECK (true);
-- CREATE POLICY "Allow all operations" ON public.audit_logs FOR ALL USING (true) WITH CHECK (true);
-- CREATE POLICY "Allow all operations" ON public.verification_events FOR ALL USING (true) WITH CHECK (true);
-- CREATE POLICY "Allow all operations" ON public.attendance_overrides FOR ALL USING (true) WITH CHECK (true);
