import dlib
import numpy as np
import face_recognition_models
import streamlit as st
import time

from src.database.db import get_all_employees, get_all_employees_for_company, get_enrolled_employees_for_subject

@st.cache_resource
def load_dlib_models():
    detector = dlib.get_frontal_face_detector() 

    sp = dlib.shape_predictor(
        face_recognition_models.pose_predictor_model_location()
    )

    facerec = dlib.face_recognition_model_v1(
        face_recognition_models.face_recognition_model_location()
    )

    return detector, sp, facerec

def call_managed_liveness_api_mock(image_np, nonce=None):
    """
    Simulates a call to a managed liveness API (e.g. AWS Rekognition, Azure Face).
    Accepts a nonce to prevent replay attacks.
    """
    # Simulate network latency
    time.sleep(0.5) 
    
    # In a real scenario, we'd send the image_np and nonce to the cloud API
    # and verify the nonce matches the one generated by the server.
    
    # Mocking a successful liveness check
    return {
        "liveness_score": 0.98,
        "is_live": True,
        "nonce_verified": True if nonce else False
    }

def get_face_embeddings(image_np, enforce_liveness=False, nonce=None):
    detector, sp, facerec = load_dlib_models()
    faces = detector(image_np, 1)

    # Fallback to OpenCV Haar Cascade if dlib HOG fails
    if len(faces) == 0:
        import cv2
        import urllib.request
        import os

        # Download haarcascade if not exists in the current working directory
        haarcascade_path = "haarcascade_frontalface_default.xml"
        if not os.path.exists(haarcascade_path):
            urllib.request.urlretrieve("https://raw.githubusercontent.com/opencv/opencv/master/data/haarcascades/haarcascade_frontalface_default.xml", haarcascade_path)
        
        face_cascade = cv2.CascadeClassifier(haarcascade_path)
        gray = cv2.cvtColor(image_np, cv2.COLOR_RGB2GRAY)
        
        # Detect faces with Haar (Highly permissive, lower minNeighbors)
        haar_faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=2, minSize=(30, 30))
        
        # Convert Haar bounding boxes (x,y,w,h) to dlib rectangles
        # dlib.rectangle needs (left, top, right, bottom)
        faces = dlib.rectangles()
        for (x, y, w, h) in haar_faces:
            faces.append(dlib.rectangle(x, y, x + w, y + h))

    encodings = []

    for face in faces:
        if enforce_liveness:
            liveness_result = call_managed_liveness_api_mock(image_np, nonce)
            if not liveness_result.get("is_live"):
                st.warning("Liveness check failed! Suspicious activity detected.")
                continue

        shape = sp(image_np, face)
        face_descriptor = facerec.compute_face_descriptor(image_np, shape, 1) # 128 embedding

        encodings.append(np.array(face_descriptor))
    return encodings

def get_employee_embeddings(company_id=None, subject_id=None):
    """
    Fetches employee embeddings from the database.
    """
    if subject_id:
        employee_db = get_enrolled_employees_for_subject(subject_id)
    elif company_id:
        employee_db = get_all_employees_for_company(company_id)
    else:
        employee_db = get_all_employees()

    if not employee_db:
        return []
    
    employees = []
    for employee in employee_db:
        embedding = employee.get('face_embedding')
        if embedding:
            employees.append({
                'employee_id': employee.get('employee_id'),
                'embedding': np.array(embedding)
            })

    return employees

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

def predict_attendance(class_image_np, company_id=None, subject_id=None, enforce_liveness=True, nonce=None):
    """
    Verifies faces in the image against enrolled employees using Cosine Similarity.
    
    Thresholds:
    Accept: > 0.50
    Review: 0.40 - 0.50
    Reject: < 0.40
    """
    encodings = get_face_embeddings(class_image_np, enforce_liveness=enforce_liveness, nonce=nonce)
    
    detected_employee = {}
    employees = get_employee_embeddings(company_id, subject_id)

    if not employees or not encodings:
        return detected_employee, [e['employee_id'] for e in employees], len(encodings)
    
    all_employee_ids = [e['employee_id'] for e in employees]

    for encoding in encodings:
        best_match_score = -1.0
        best_match_id = None
        
        for emp in employees:
            sim = cosine_similarity(encoding, emp['embedding'])
            if sim > best_match_score:
                best_match_score = sim
                best_match_id = emp['employee_id']
                
        # Apply Thresholds
        if best_match_score > 0.50:
            decision = 'Accepted'
        elif best_match_score >= 0.40:
            decision = 'Review'
        else:
            decision = 'Rejected'
            
        if decision in ['Accepted', 'Review'] and best_match_id is not None:
            detected_employee[best_match_id] = {
                'similarity_score': float(best_match_score),
                'decision': decision
            }
            
    return detected_employee, all_employee_ids, len(encodings)
